kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
localAPIEndpoint:
  advertiseAddress: {{ hostvars[inventory_hostname].ansible_facts.eth1.ipv4.address }}
  bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  name: {{ hostvars[inventory_hostname].ansible_hostname }}
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: {{ kube_version }}
apiServer:
  timeoutForControlPlane: 4m0s
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
