apiVersion: kubeadm.k8s.io/v1beta4
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ control_pane_eth1_ip }}
  bindPort: {{ api_bind_port }}
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: {{ control_pane_hostname }}
  taints: null
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
---
apiServer:
  certSANs:
    - "{{ control_pane_eth1_ip }}"
    - "{{ control_pane_hostname }}"
  extraArgs:
    - name: "bind-address"
      value: "{{ control_pane_eth1_ip }}"
    - name: "advertise-address"
      value: "{{ control_pane_eth1_ip }}"
apiVersion: kubeadm.k8s.io/v1beta4
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    - name: "bind-address"
      value: "{{ control_pane_eth1_ip }}"
dns: {}
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
    - name: "listen-client-urls"
      value: "https://{{ control_pane_eth1_ip }}:{{ etcd_client_port}}"
    - name: "advertise-client-urls"
      value: "https://{{ control_pane_eth1_ip }}:{{ etcd_client_port}}"
    - name: "listen-peer-urls"
      value: "https://{{ control_pane_eth1_ip }}:{{ etcd_peer_port}}"
    - name: "initial-advertise-peer-urls"
      value: "https://{{ control_pane_eth1_ip }}:{{ etcd_peer_port}}"
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: {{ kube_full_version }}
networking:
  dnsDomain: cluster.local
  serviceSubnet: "{{ pod_network_cidr }}"
proxy: {}
scheduler:
  extraArgs:
    - name: "bind-address"
      value: "{{ control_pane_eth1_ip }}"
