---

modules_conf_path: /etc/modules-load.d/containerd.conf
sysctl_conf_path: /etc/sysctl.d/99-kubernetes-cri.conf

kernel_modules:
  - overlay
  - br_netfilter

sysctl_params:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1