---

- name: Install utils packages
  include_tasks: utils.yml

- name: Install containerd
  include_tasks: containerd.yml

- name: Install & configure kube packages
  include_tasks: kube_packages.yml

- name: Systemd actions
  meta: flush_handlers