---

# Set /etc/hosts
- name: Retrieve network facts for each server
  setup:
    gather_subset: network
  delegate_to: "{{ item }}"
  delegate_facts: yes
  loop: "{{ groups.all }}"
  run_once: yes

- name: Remove extra entries in /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regex: "{{ hostvars[inventory_hostname].ansible_hostname }}"
    state: absent

- name: Add all cluster nodes to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regex: "^{{ hostvars[item].ansible_facts.eth1.ipv4.address }}"
    line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }}\t{{ hostvars[item].ansible_hostname }}"
    state: present
  loop: "{{ groups.all | list }}"

# Upgrade packages & kernel
- name: LTS kernel
  include_tasks: upgrade_kernel.yml

- name: Apply system customizations
  include_tasks: system.yml

- name: Setup lab user
  include_tasks: user.yml