---

- name: Configure servers & Install packages
  hosts: all

  pre_tasks:
    - name: Required ansible python libs
      import_tasks: pre_tasks/python_libs.yml

  roles:
    - name: Setup VMs
      role: setup

    - name: Install packages
      role: packages

    - name: Initialize K8s cluster
      role: cluster