---

- name: Configure servers & Install packages
  hosts: all

  pre_tasks:
    - name: Prerequisites
      import_tasks: pre_tasks/prerequisites.yml

  roles:
    - name: Setup VMs
      role: setup

    - name: Install packages
      role: packages

    - name: Initialize K8s cluster
      role: cluster