---

- name: Configure servers & Install packages
  hosts: all

  roles:
    - name: Setup VMs
      role: setup

    - name: Install packages
      role: packages

- name: Init cluster
  hosts: control_pane[0]

  roles:
    - name: Create K8s cluster
      role: cluster
